version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432